######################################################################
# Automatically generated by qmake (1.03a) Tue Jan 14 18:13:59 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += qcontrols.h
SOURCES += qcontrols.cpp \
           test_cgrid.cpp \
           test_cmap_node.cpp \
           test_gstlnode.cpp \
           test_pointset.cpp \
           test_slice.cpp \
           test_wireframe_overlay.cpp

TARGET=oinv



contains( TEMPLATE, lib ) {
    DESTDIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM/obj/tests/gui/oinv
}
contains( TEMPLATE, app ) {
    DESTDIR += $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM/obj/tests/gui/oinv
}


include( $$GSTLAPPLI_HOME/config.qmake )

exists( MMakefile ) {
   include( MMakefile )
}

