######################################################################
# Automatically generated by qmake (1.02a) Wed Dec 4 15:32:48 2002
######################################################################

TEMPLATE = app
CONFIG -= moc

# Input
SOURCES += test_channels.cpp \
           test_manager.cpp \
           test_splitname.cpp \
           test_string_manip.cpp \
           test_utils.cpp

TARGET=utils



contains( TEMPLATE, lib ) {
    DESTDIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM/obj/tests/utils
}
contains( TEMPLATE, app ) {
    DESTDIR += $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM/obj/tests/utils
}


include( $$GSTLAPPLI_HOME/config.qmake )

exists( MMakefile ) {
   include( MMakefile )
}

