#ifndef _pqRadialDistanceWidget_h
#define _pqRadialDistanceWidget_h

#include "pqProxy.h"
#include "pq3DWidget.h"
#include "pqComponentsExport.h"
#include "pqAutoGeneratedObjectPanel.h"

class pqRadialDistanceWidget : public pqAutoGeneratedObjectPanel 
{
  Q_OBJECT
  
public:

  pqRadialDistanceWidget(pqProxy* proxy, QWidget* p = NULL);
  ~pqRadialDistanceWidget();

  protected:
    /// populate widgets with properties from the server manager
    virtual void linkServerManagerProperties();

};

#endif

