######################################################################
# Automatically generated by qmake (1.02a) Mon Jun 3 17:07:08 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += grid_io gui_oi
