##############################################################
# Automatically generated by qmake Sun May 19 20:55:49 2002
##############################################################

TEMPLATE = subdirs

SUBDIRS = qtplugins gui
