######################################################################
# Automatically generated by qmake (1.02a) Mon Jun 24 18:23:07 2002
######################################################################

TEMPLATE = lib
DEPENDPATH += parser

# Input
HEADERS += surface.h parser/parser.h
SOURCES += surface.cpp parser/parser.cpp

TARGET=GsTLAppli_test_libs



contains( TEMPLATE, lib ) {
    DESTDIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM/obj/tests/test_libs
}
contains( TEMPLATE, app ) {
    DESTDIR += $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM/obj/tests/test_libs
}


include( $$GSTLAPPLI_HOME/config.qmake )

exists( MMakefile ) {
   include( MMakefile )
}

