######################################################################
# Automatically generated by qmake (1.02a) Tue Sep 3 11:19:16 2002
######################################################################

TEMPLATE = app

# Input
HEADERS += parameters.h
SOURCES += essai_xml.cc \
           grid_itr.cpp \
           Parameters.cc \
           parameters.cpp \
           snesim2.cpp \
           test_data_array.cpp \
           test_gridcursor.cpp \
           test_itr.cpp \
           test_strati_grid.cpp \
           test_topo.cpp

TARGET=grid



contains( TEMPLATE, lib ) {
    DESTDIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM/obj/tests/grid/grid
}
contains( TEMPLATE, app ) {
    DESTDIR += $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM/obj/tests/grid/grid
}


include( $$GSTLAPPLI_HOME/config.qmake )

exists( MMakefile ) {
   include( MMakefile )
}

