######################################################################
# Automatically generated by qmake (1.03a) Mon Feb 17 19:42:06 2003
######################################################################

TEMPLATE = app
DEPENDPATH += plugin

# Input
HEADERS += input_widget.h plugin/bidon.h
INTERFACES += dynamic.ui
SOURCES += input_widget.cpp \
           test_cokriging.cpp \
           test_gui.cpp \
           test_kriging_lvm.cpp \
           test_parameters_handler.cpp \
           test_sgsim.cpp \
           test_simple_kriging.cpp \
           test_snesim.cpp \
           plugin/bidon.cpp

TARGET=geostat



contains( TEMPLATE, lib ) {
    DESTDIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM/obj/tests/geostat
}
contains( TEMPLATE, app ) {
    DESTDIR += $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM/obj/tests/geostat
}


include( $$GSTLAPPLI_HOME/config.qmake )

exists( MMakefile ) {
   include( MMakefile )
}

