######################################################################
# Automatically generated by qmake (1.02a) Mon Jun 3 17:07:08 2002
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += test_libs utils utils2 gui grid geostat
