######################################################################
# Automatically generated by qmake (1.03a) Fri Jan 24 16:50:57 2003
######################################################################

TEMPLATE = app
DEPENDPATH += appli oinv utils

# Input
HEADERS += input_widget.h oinv/qcontrols.h
SOURCES += input_widget.cpp \
           test_gui.cpp \
           appli/test_appli.cpp \
           appli/test_oinv_view.cpp \
           oinv/qcontrols.cpp \
           oinv/test_cgrid.cpp \
           oinv/test_cmap_node.cpp \
           oinv/test_gstlnode.cpp \
           oinv/test_pointset.cpp \
           oinv/test_slice.cpp \
           oinv/test_wireframe_overlay.cpp \
           utils/test_parameters_form.cpp

TARGET=gui



contains( TEMPLATE, lib ) {
    DESTDIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/lib/$$CUR_PLATFORM/obj/tests/gui
}
contains( TEMPLATE, app ) {
    DESTDIR += $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM
    OBJECTS_DIR = $$GSTLAPPLI_HOME/bin/$$CUR_PLATFORM/obj/tests/gui
}


include( $$GSTLAPPLI_HOME/config.qmake )

exists( MMakefile ) {
   include( MMakefile )
}

