######################################################################
# Automatically generated by qmake (1.03a) Wed Jan 29 22:12:25 2003
######################################################################

TEMPLATE = app

# Input
SOURCES += test_selectors.cpp

TARGET=test_selectors



exists( MMakefile ) {
   include( MMakefile )
}

